image: golang:1.10.3
stages:
  - build

before_script:
  - mkdir -p /go/src/gitlab.com/MikeModder /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/MikeModder/Wonky-Shell
  - go get -u github.com/JoshuaDoes/govvv
  - go get -u github.com/c-bata/go-prompt
  - go get -u github.com/mattn/go-tty
  - go get -u github.com/mattn/go-colorable
  - go get -u github.com/mattn/go-isatty
  - which govvv

build:
  stage: build
  artifacts:
      paths:
        - out/
  script:
    - rm -rf out/
    - mkdir out
    - GOOS=windows GOARCH=amd64 govvv build -o out/Wonky-Shell-win32.exe
    - GOOS=windows GOARCH=386   govvv build -o out/Wonky-Shell-win64.exe
    - GOOS=darwin  GOARCH=amd64 govvv build -o out/Wonky-Shell-mac64
    - GOOS=linux   GOARCH=amd64 govvv build -o out/Wonky-Shell-lin64
    - GOOS=linux   GOARCH=386   govvv build -o out/Wonky-Shell-lin32